# template for KubernetesPodOperator
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pod-template-config"
data:
  pod_template.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: airflow-task-pod
      labels:
        app: airflow
    spec:
      restartPolicy: Never
      containers:
        - name: airflow-task
          image: your-airflow-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: your_sql_alchemy_connection_string
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW__KUBERNETES__NAMESPACE
              value: airflow
            - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY
              value: your-airflow-image
            - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG
              value: latest
          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "0.5"
              memory: "1Gi"
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
