airflow:
  executor: KubernetesExecutor
  image:
    repository: your-docker-repo/airflow
    tag: latest
  namespace: airflow
  volumes:
    - name: example-volume-1
      persistentVolumeClaim:
        claimName: example-claim-1
    - name: example-volume-2
      persistentVolumeClaim:
        claimName: example-claim-2
  volumeMounts:
    - name: example-volume-1
      mountPath: /path/inside/container1
    - name: example-volume-2
      mountPath: /path/inside/container2
  env:
    - name: EXAMPLE_ENV_VAR_1
      value: example_value_1
    - name: EXAMPLE_ENV_VAR_2
      value: example_value_2
