apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
  labels:
    app: airflow
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:2.3.3
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "KubernetesExecutor"
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: "/opt/airflow/dags"
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: airflow.cfg
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: fernet_key
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY
              value: "/opt/airflow/logs/scheduler"
            - name: AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE
              value: "/opt/airflow/pod_templates/pod_template.yaml"
          volumeMounts:
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
            - name: airflow-pod-template
              mountPath: /opt/airflow/pod_templates/pod_template.yaml
              subPath: pod_template.yaml
            - name: airflow-logs
              mountPath: /opt/airflow/logs
          ports:
            - containerPort: 8793  # Health check port
      volumes:
        - name: airflow-config
          configMap:
            name: airflow-config
        - name: airflow-pod-template
          configMap:
            name: airflow-pod-template
        - name: airflow-logs
          emptyDir: {}
